from .tui import Component as Component

class Markdown(Component):
    def __init__(
        self,
        text: str = ...,
        padding_x: int = ...,
        padding_y: int = ...,
        width: int | None = ...,
        code_theme: str = ...,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_code_theme(self, theme: str) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class RichText(Component):
    def __init__(
        self, text: str = ..., padding_x: int = ..., padding_y: int = ...
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class RichTable(Component):
    def __init__(
        self, title: str = ..., padding_x: int = ..., padding_y: int = ...
    ) -> None: ...
    def add_column(
        self, name: str, style: str | None = ..., justify: str = ...
    ) -> None: ...
    def add_row(self, *values: str) -> None: ...
    def clear_rows(self) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...
