import abc
from abc import ABC, abstractmethod
from collections.abc import Callable as Callable
from dataclasses import dataclass
from typing import Any

from .terminal import Terminal as Terminal

CURSOR_MARKER: str

class Component(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def render(self, width: int) -> list[str]: ...
    def handle_input(self, data: str) -> None: ...
    @property
    def wants_key_release(self) -> bool: ...
    @abstractmethod
    def invalidate(self) -> None: ...

class Focusable(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def focused(self) -> bool: ...
    @focused.setter
    @abstractmethod
    def focused(self, value: bool) -> None: ...

def is_focusable(component: Component | None) -> bool: ...
type SizeValue = int | str
type OverlayAnchor = str

@dataclass
class OverlayMargin:
    top: int = ...
    right: int = ...
    bottom: int = ...
    left: int = ...

@dataclass
class OverlayOptions:
    width: SizeValue | None = ...
    min_width: int | None = ...
    max_height: SizeValue | None = ...
    anchor: OverlayAnchor = ...
    offset_x: int = ...
    offset_y: int = ...
    row: SizeValue | None = ...
    col: SizeValue | None = ...
    margin: OverlayMargin | int | None = ...
    visible: Callable[[int, int], bool] | None = ...

@dataclass
class OverlayHandle:
    overlay: Any
    def hide(self) -> None: ...
    def set_hidden(self, hidden: bool) -> None: ...
    def is_hidden(self) -> bool: ...

class Container(Component):
    children: list[Component]
    def __init__(self) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def remove_child(self, component: Component) -> None: ...
    def clear(self) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class TUI(Container):
    terminal: Terminal
    on_debug: Callable[[], None] | None
    def __init__(self, terminal: Terminal, show_hardware_cursor: bool = ..., clear_on_shrink: bool = ..., use_alternate_buffer: bool = ...) -> None: ...
    @property
    def clear_on_shrink(self) -> bool: ...
    @clear_on_shrink.setter
    def clear_on_shrink(self, enabled: bool) -> None: ...
    def set_focus(self, component: Component | None) -> None: ...
    def show_overlay(self, component: Component, options: OverlayOptions | None = ...) -> OverlayHandle: ...
    def hide_overlay(self) -> None: ...
    def has_overlay(self) -> bool: ...
    def invalidate(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def add_input_listener(self, listener: Callable[[str], dict | None]) -> Callable[[], None]: ...
    def request_render(self, force: bool = ...) -> None: ...
    def handle_input(self, data: str) -> None: ...
    def render_frame(self) -> None: ...
    def run_frame(self) -> bool: ...
    def run(self) -> None: ...
