import abc
from abc import ABC, abstractmethod

class Terminal(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def write(self, data: str) -> None: ...
    @abstractmethod
    def read(self, timeout: float = ...) -> str | None: ...
    @abstractmethod
    def read_sequence(self, timeout: float = ...) -> str | None: ...
    @abstractmethod
    def get_size(self) -> tuple[int, int]: ...
    @abstractmethod
    def clear(self) -> None: ...
    @abstractmethod
    def move_cursor(self, row: int, col: int) -> None: ...
    @abstractmethod
    def hide_cursor(self) -> None: ...
    @abstractmethod
    def show_cursor(self) -> None: ...
    @abstractmethod
    def set_raw_mode(self) -> None: ...
    @abstractmethod
    def restore_mode(self) -> None: ...
    @abstractmethod
    def move_cursor_up(self, n: int = ...) -> str: ...
    @abstractmethod
    def move_cursor_down(self, n: int = ...) -> str: ...

class ProcessTerminal(Terminal):
    def __init__(self) -> None: ...
    def write(self, data: str) -> None: ...
    def read(self, timeout: float = ...) -> str | None: ...
    def read_sequence(self, timeout: float = ...) -> str | None: ...
    def get_size(self) -> tuple[int, int]: ...
    def clear(self) -> None: ...
    def move_cursor(self, row: int, col: int) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...
    def set_raw_mode(self) -> None: ...
    def restore_mode(self) -> None: ...
    def move_cursor_up(self, n: int = ...) -> str: ...
    def move_cursor_down(self, n: int = ...) -> str: ...

class MockTerminal(Terminal):
    cols: int
    rows: int
    cursor_visible: bool
    def __init__(self, cols: int = ..., rows: int = ...) -> None: ...
    def write(self, data: str) -> None: ...
    def read(self, timeout: float = ...) -> str | None: ...
    def read_sequence(self, timeout: float = ...) -> str | None: ...
    def get_size(self) -> tuple[int, int]: ...
    def clear(self) -> None: ...
    def move_cursor(self, row: int, col: int) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...
    def set_raw_mode(self) -> None: ...
    def restore_mode(self) -> None: ...
    def move_cursor_up(self, n: int = ...) -> str: ...
    def move_cursor_down(self, n: int = ...) -> str: ...
    def queue_input(self, data: str) -> None: ...
    def queue_input_sequence(self, sequence: str) -> None: ...
    def get_output(self) -> str: ...
    def clear_buffer(self) -> None: ...
