from .keys import Key as Key, matches_key as matches_key
from .tui import CURSOR_MARKER as CURSOR_MARKER, Component as Component, Focusable as Focusable
from .utils import truncate_to_width as truncate_to_width, visible_width as visible_width, wrap_text_with_ansi as wrap_text_with_ansi
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from dataclasses import dataclass

ANSI_RESET: str
ANSI_RESET_LEN: Incomplete

class Text(Component):
    def __init__(self, text: str = '', padding_x: int = 1, padding_y: int = 1, custom_bg_fn: Callable[[str], str] | None = None) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_custom_bg_fn(self, custom_bg_fn: Callable[[str], str] | None) -> None: ...
    def render(self, width: int) -> list[str]: ...

class Box(Component):
    children: list[Component]
    def __init__(self, padding_x: int = 1, padding_y: int = 1, bg_fn: Callable[[str], str] | None = None) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def remove_child(self, component: Component) -> None: ...
    def clear(self) -> None: ...
    def set_bg_fn(self, bg_fn: Callable[[str], str] | None) -> None: ...
    def render(self, width: int) -> list[str]: ...

class BorderedBox(Component):
    TOP_LEFT: str
    TOP_RIGHT: str
    BOTTOM_LEFT: str
    BOTTOM_RIGHT: str
    HORIZONTAL: str
    VERTICAL: str
    T_LEFT: str
    T_RIGHT: str
    children: list[Component]
    def __init__(self, padding_x: int = 1, padding_y: int = 0, min_width: int = 10, max_width: int | None = None, title: str | None = None) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_rich_title(self, markup: str) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def remove_child(self, component: Component) -> None: ...
    def clear(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class Spacer(Component):
    def __init__(self, height: int = 1) -> None: ...
    def render(self, width: int) -> list[str]: ...

@dataclass
class SelectItem:
    value: str
    label: str
    description: str | None = ...

@dataclass
class SelectListTheme:
    selected_prefix: Callable[[str], str] = ...
    selected_text: Callable[[str], str] = ...
    description: Callable[[str], str] = ...
    scroll_info: Callable[[str], str] = ...
    no_match: Callable[[str], str] = ...

class SelectList(Component):
    on_select: Callable[[SelectItem], None] | None
    on_cancel: Callable[[], None] | None
    on_selection_change: Callable[[SelectItem], None] | None
    def __init__(self, items: list[SelectItem], max_visible: int, theme: SelectListTheme) -> None: ...
    def set_filter(self, filter_text: str) -> None: ...
    def set_selected_index(self, index: int) -> None: ...
    def get_selected_item(self) -> SelectItem | None: ...
    def render(self, width: int) -> list[str]: ...
    def handle_input(self, data: str) -> None: ...

class Input(Component, Focusable):
    on_submit: Callable[[str], None] | None
    on_cancel: Callable[[], None] | None
    def __init__(self, placeholder: str = '', password: bool = False, max_length: int | None = None) -> None: ...
    @property
    def focused(self) -> bool: ...
    @focused.setter
    def focused(self, value: bool) -> None: ...
    def get_value(self) -> str: ...
    def set_value(self, text: str) -> None: ...
    def render(self, width: int) -> list[str]: ...
    def handle_input(self, data: str) -> None: ...
