"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING
from .tui import Component, Focusable
from collections.abc import Callable

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
_RICH_REQUIRED_MSG = ...
ANSI_RESET = ...
ANSI_RESET_LEN = ...
class Text(Component):
    """Text component - displays multi-line text with word wrapping."""
    def __init__(self, text: str = ..., padding_x: int = ..., padding_y: int = ..., custom_bg_fn: Callable[[str], str] | None = ...) -> None:
        ...
    
    def set_text(self, text: str) -> None:
        """Update the text content."""
        ...
    
    def set_custom_bg_fn(self, custom_bg_fn: Callable[[str], str] | None) -> None:
        """Set custom background function."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render text with padding and wrapping."""
        ...
    


class Box(Component):
    """Box component - a container that applies padding and background."""
    def __init__(self, padding_x: int = ..., padding_y: int = ..., bg_fn: Callable[[str], str] | None = ...) -> None:
        ...
    
    def add_child(self, component: Component) -> None:
        """Add a child component."""
        ...
    
    def remove_child(self, component: Component) -> None:
        """Remove a child component."""
        ...
    
    def clear(self) -> None:
        """Remove all children."""
        ...
    
    def set_bg_fn(self, bg_fn: Callable[[str], str] | None) -> None:
        """Set background function."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render box with children."""
        ...
    


class BorderedBox(Component):
    """A box with borders that intelligently wraps content to fit inside.

    Unlike Box which just adds padding, BorderedBox draws borders and
    wraps content to fit within the content area, maintaining the box shape.
    """
    TOP_LEFT = ...
    TOP_RIGHT = ...
    BOTTOM_LEFT = ...
    BOTTOM_RIGHT = ...
    HORIZONTAL = ...
    VERTICAL = ...
    T_LEFT = ...
    T_RIGHT = ...
    def __init__(self, padding_x: int = ..., padding_y: int = ..., min_width: int = ..., max_width: int | None = ..., title: str | None = ...) -> None:
        ...
    
    def set_title(self, title: str) -> None:
        """Set the box title.

        Args:
            title: Plain text or ANSI-escaped string
        """
        ...
    
    def set_rich_title(self, markup: str) -> None:
        """Set the box title using Rich markup.

        Requires the 'rich' extra: pip install pypitui[rich]

        Args:
            markup: Rich markup string (e.g., "[bold cyan]Title[/bold cyan]")

        Example:
            box = BorderedBox()
            box.set_rich_title("[bold cyan]My Panel[/bold cyan]")
        """
        ...
    
    def add_child(self, component: Component) -> None:
        """Add a child component."""
        ...
    
    def remove_child(self, component: Component) -> None:
        """Remove a child component."""
        ...
    
    def clear(self) -> None:
        """Remove all children."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render bordered box with wrapped content.

        The box will use the requested width if possible, but content
        will be wrapped to fit within the borders.
        """
        ...
    


class Spacer(Component):
    """Spacer component - empty vertical space."""
    def __init__(self, height: int = ...) -> None:
        ...
    
    def render(self, width: int) -> list[str]:
        """Render empty lines."""
        ...
    


@dataclass
class SelectItem:
    """Item for SelectList."""
    value: str
    label: str
    description: str | None = ...


@dataclass
class SelectListTheme:
    """Theme for SelectList."""
    selected_prefix: Callable[[str], str] = ...
    selected_text: Callable[[str], str] = ...
    description: Callable[[str], str] = ...
    scroll_info: Callable[[str], str] = ...
    no_match: Callable[[str], str] = ...


class SelectList(Component):
    """Selectable list component."""
    def __init__(self, items: list[SelectItem], max_visible: int, theme: SelectListTheme) -> None:
        ...
    
    def set_filter(self, filter_text: str) -> None:
        """Set filter text."""
        ...
    
    def set_selected_index(self, index: int) -> None:
        """Set selected index."""
        ...
    
    def get_selected_item(self) -> SelectItem | None:
        """Get currently selected item."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render the select list."""
        ...
    
    def handle_input(self, data: str) -> None:
        """Handle keyboard input."""
        ...
    


class Input(Component, Focusable):
    """Text input component with cursor support."""
    def __init__(self, placeholder: str = ..., password: bool = ..., max_length: int | None = ...) -> None:
        ...
    
    @property
    def focused(self) -> bool:
        ...
    
    @focused.setter
    def focused(self, value: bool) -> None:
        ...
    
    def get_value(self) -> str:
        """Get current input value."""
        ...
    
    def set_value(self, text: str) -> None:
        """Set input value."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render input with cursor."""
        ...
    
    def handle_input(self, data: str) -> None:
        """Handle keyboard input."""
        ...
    


