from types import TracebackType
from typing import Self

class MockTerminal:
    def __init__(self, width: int = 80, height: int = 24) -> None: ...
    def write(self, data: str | bytes) -> None: ...
    def move_cursor(self, col: int, row: int) -> None: ...
    def clear_line(self) -> None: ...
    def clear_screen(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...
    def get_escape_count(self) -> int: ...
    def get_write_count(self) -> int: ...
    def reset_counts(self) -> None: ...
    def get_output(self) -> bytes: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, _exc_type: type[BaseException] | None, _exc_val: BaseException | None, _exc_tb: TracebackType | None) -> None: ...
