from .component import Component as Component
from dataclasses import dataclass

@dataclass(frozen=True)
class OverlayPosition:
    row: int
    col: int = ...
    width: int = ...
    height: int = ...
    anchor: str | None = ...

@dataclass
class Overlay:
    content: Component
    position: OverlayPosition
    visible: bool = ...
    z_index: int = ...
