"""
This type stub file was generated by pyright.
"""

from typing import Literal
from .tui import Component

"""
This type stub file was generated by pyright.
"""
_RICH_REQUIRED_MSG = ...
class Markdown(Component):
    """Render markdown using Rich library.

    Requires: pip install pypitui[rich]

    Features:
    - Headings, bold, italic, code blocks
    - Lists, links, blockquotes
    - Syntax highlighting in code blocks
    - Tables
    """
    def __init__(self, text: str = ..., padding_x: int = ..., padding_y: int = ..., width: int | None = ..., code_theme: str = ...) -> None:
        ...
    
    def set_text(self, text: str) -> None:
        """Update markdown content."""
        ...
    
    def set_code_theme(self, theme: str) -> None:
        """Set code highlighting theme."""
        ...
    
    def invalidate(self) -> None:
        """Clear render cache."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render markdown to lines."""
        ...
    


class RichText(Component):
    """Render Rich text/markup.

    Requires: pip install pypitui[rich]

    Example:
        RichText("[bold red]Hello[/bold red] World!")
    """
    def __init__(self, text: str = ..., padding_x: int = ..., padding_y: int = ...) -> None:
        ...
    
    def set_text(self, text: str) -> None:
        """Update text content."""
        ...
    
    def invalidate(self) -> None:
        """Clear cache."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render to lines."""
        ...
    


class RichTable(Component):
    """Render Rich tables.

    Requires: pip install pypitui[rich]

    Example:
        table = RichTable(title="My Table")
        table.add_column("Name", style="cyan")
        table.add_column("Value", style="green")
        table.add_row("Item 1", "100")
    """
    def __init__(self, title: str = ..., padding_x: int = ..., padding_y: int = ...) -> None:
        ...
    
    def add_column(self, name: str, style: str | None = ..., justify: Literal["default", "left", "center", "right", "full"] = ...) -> None:
        """Add a column."""
        ...
    
    def add_row(self, *values: str) -> None:
        """Add a row."""
        ...
    
    def clear_rows(self) -> None:
        """Clear all rows."""
        ...
    
    def invalidate(self) -> None:
        """Clear cache."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render to lines."""
        ...
    


def rich_to_ansi(markup: str) -> str:
    """Convert Rich markup to ANSI codes.

    Use this to convert Rich markup strings for components that expect
    plain ANSI strings (like SelectList items).

    Args:
        markup: Rich markup string (e.g., "[bold cyan]Hello[/bold cyan]")

    Returns:
        ANSI-escaped string ready for display

    Example:
        from pypitui.rich_components import rich_to_ansi

        # Rich markup for regular components
        tui.add_child(RichText("[bold cyan]Hello[/bold cyan]"))

        # Convert to ANSI for SelectList
        label = rich_to_ansi("[bold cyan]Menu Item[/bold cyan]")
        items = [SelectItem("key", label,
                            rich_to_ansi("[dim]Description[/dim]"))]
    """
    ...

def rich_color_to_ansi(color: str) -> str:
    """Convert a Rich color name to its ANSI escape code.

    Args:
        color: Rich color name (e.g., "bright_cyan", "red", "bold magenta")

    Returns:
        ANSI escape code string, or empty string if color is empty

    Example:
        from pypitui.rich_components import rich_color_to_ansi

        cyan = rich_color_to_ansi("bright_cyan")  # "\\x1b[96m"
        bold_red = rich_color_to_ansi("bold red")  # "\\x1b[1;31m"
    """
    ...

