from .tui import Component as Component
from .utils import visible_width as visible_width
from typing import Literal

class Markdown(Component):
    def __init__(self, text: str = '', padding_x: int = 0, padding_y: int = 0, width: int | None = None, code_theme: str = 'monokai') -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_code_theme(self, theme: str) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class RichText(Component):
    def __init__(self, text: str = '', padding_x: int = 0, padding_y: int = 0) -> None: ...
    def set_text(self, text: str) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class RichTable(Component):
    def __init__(self, title: str = '', padding_x: int = 0, padding_y: int = 0) -> None: ...
    def add_column(self, name: str, style: str | None = None, justify: Literal['default', 'left', 'center', 'right', 'full'] = 'left') -> None: ...
    def add_row(self, *values: str) -> None: ...
    def clear_rows(self) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

def rich_to_ansi(markup: str) -> str: ...
def rich_color_to_ansi(color: str) -> str: ...
