from types import TracebackType
from typing import BinaryIO, Self

class Terminal:
    def __init__(self, fd: int | None = None, buffer: BinaryIO | None = None) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
    def write(self, data: str | bytes) -> None: ...
    def move_cursor(self, col: int, row: int) -> None: ...
