"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, TYPE_CHECKING, TypeGuard
from collections.abc import Callable
from .terminal import Terminal

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
__all__ = ["CURSOR_MARKER", "FRAME_TIME", "Component", "Focusable", "is_focusable", "OverlayMargin", "OverlayOptions", "OverlayHandle", "Container", "TUI"]
CURSOR_MARKER = ...
FRAME_TIME = ...
class Component(ABC):
    """Component interface - all components must implement this.

    Components are the building blocks of the TUI, similar to React components.
    Each component is responsible for rendering itself to a list of strings.

    Note: _parent is set by Container.add_child() when this component
    is added to a container. Accessing _parent before add_child() will
    raise AttributeError.
    """
    _parent: Component | None = ...
    @abstractmethod
    def render(self, width: int) -> list[str]:
        """Render the component to lines for the given viewport width.

        Args:
            width: Current viewport width in columns

        Returns:
            Array of strings, each representing a line.
            Each line must not exceed `width` visible characters.
        """
        ...
    
    def handle_input(self, data: str) -> None:
        """Optional handler for keyboard input when component has focus.

        Args:
            data: Raw input data from terminal
        """
        ...
    
    @property
    def wants_key_release(self) -> bool:
        """If True, component receives key release events (Kitty protocol).

        Default is False - release events are filtered out.
        """
        ...
    


class Focusable(ABC):
    """Interface for components that can receive focus and display a
    hardware cursor.

    When focused, the component should emit CURSOR_MARKER at the cursor
    position in its render output. TUI will find this marker and position
    the hardware cursor there for proper IME candidate window positioning.
    """
    @property
    @abstractmethod
    def focused(self) -> bool:
        """Set by TUI when focus changes.

        Component should emit CURSOR_MARKER when True.
        """
        ...
    
    @focused.setter
    @abstractmethod
    def focused(self, value: bool) -> None:
        ...
    


def is_focusable(component: Component | Focusable | None) -> TypeGuard[Focusable]:
    """Type guard to check if a component implements Focusable."""
    ...

SizeValue = int | str
OverlayAnchor = str
@dataclass
class OverlayMargin:
    """Margin configuration for overlays."""
    top: int = ...
    right: int = ...
    bottom: int = ...
    left: int = ...


@dataclass
class OverlayOptions:
    """Options for overlay positioning and sizing.

    Values can be absolute numbers or percentage strings (e.g., "50%").
    """
    width: SizeValue | None = ...
    min_width: int | None = ...
    max_height: SizeValue | None = ...
    anchor: OverlayAnchor = ...
    offset_x: int = ...
    offset_y: int = ...
    row: SizeValue | None = ...
    col: SizeValue | None = ...
    margin: OverlayMargin | int | None = ...
    visible: Callable[[int, int], bool] | None = ...


@dataclass
class OverlayHandle:
    """Handle returned by show_overlay for controlling the overlay."""
    overlay: _OverlayEntry
    def hide(self) -> None:
        """Permanently remove the overlay (cannot be shown again)."""
        ...
    
    def set_hidden(self, hidden: bool) -> None:
        """Temporarily hide or show the overlay."""
        ...
    
    def is_hidden(self) -> bool:
        """Check if overlay is temporarily hidden."""
        ...
    


@dataclass
class _OverlayEntry:
    """Internal overlay entry."""
    component: Component
    options: OverlayOptions
    hidden: bool = ...
    closed: bool = ...
    previous_focus: Component | Focusable | None = ...


class Container(Component):
    """Container - a component that contains other components.

    Components are arranged vertically in the order they were added.
    """
    def __init__(self) -> None:
        ...
    
    def add_child(self, component: Component) -> None:
        """Add a child component.

        Sets component._parent = self so the component can bubble
        up invalidation requests.
        """
        ...
    
    def remove_child(self, component: Component) -> None:
        """Remove a child component.

        Removes component._parent to clean up the reference.
        """
        ...
    
    def clear(self) -> None:
        """Remove all child components.

        ⚠️⚠️⚠️ WARNING: DO NOT USE THIS FOR SCREEN SWITCHING ⚠️⚠️⚠️

        This method removes all children but preserves _previous_lines. If you
        clear() and then re-add content, you defeat differential rendering.

        For streaming content that grows incrementally:
            - Just add_child() new content
            - Don't call clear()
            - Old content flows into scrollback naturally

        For screen switching, use one of these patterns:

        Pattern 1 - Root Container (RECOMMENDED):
            self.root = Container()
            tui.add_child(self.root)

            # Switch screens:
            self.root.children.clear()  # Clear container, not TUI
            self.root.add_child(new_screen_content)

        Pattern 2 - Reusable Component:
            class ScreenManager(Component):
                def __init__(self):
                    self.current = None

                def switch_to(self, screen):
                    self.current = screen

                def render(self, width):
                    return self.current.render(width) if self.current else []

            manager = ScreenManager()
            tui.add_child(manager)
            manager.switch_to(new_screen)

        WHY THIS MATTERS:
            - TUI uses _previous_lines for differential rendering
            - clear() + re-add forces full re-render of all lines
            - Proper patterns only update what actually changed
        """
        ...
    
    def render(self, width: int) -> list[str]:
        """Render all children vertically."""
        ...
    


class TUI(Container):
    """Main class for managing terminal UI with differential rendering.

    The TUI manages the terminal state, handles input, and renders components
    efficiently by only updating changed lines.

    IMPORTANT: Reuse TUI instances when switching screens. Creating new TUI
    instances loses the _previous_lines state needed for differential
    rendering, causing ghost content from previous screens. Instead, call
    tui.clear() to remove children, then add new children - the existing
    _previous_lines will ensure old content is properly cleared.

    Example:
        # WRONG - loses differential rendering state
        self.tui = TUI(terminal)
        self.tui.add_child(...)

        # RIGHT - reuse TUI, preserves _previous_lines
        self.tui.clear()  # Remove old children
        self.tui.add_child(...)  # Add new content
    """
    _SEGMENT_RESET = ...
    def __init__(self, terminal: Terminal, show_hardware_cursor: bool = ...) -> None:
        ...
    
    def set_focus(self, component: Component | Focusable | None) -> None:
        """Set the focused component."""
        ...
    
    def show_overlay(self, component: Component, options: OverlayOptions | None = ...) -> OverlayHandle:
        """Show an overlay component with configurable positioning and sizing.

        Args:
            component: The component to display as overlay
            options: Positioning and sizing options

        Returns:
            Handle to control the overlay's visibility
        """
        ...
    
    def hide_overlay(self) -> None:
        """Hide the topmost overlay and restore previous focus."""
        ...
    
    def has_overlay(self) -> bool:
        """Check if there are any visible overlays."""
        ...
    
    def render(self, width: int) -> list[str]:
        """Render all children."""
        ...
    
    def start(self) -> None:
        """Start the TUI - set up terminal for rendering."""
        ...
    
    def stop(self) -> None:
        """Stop the TUI - restore terminal state."""
        ...
    
    def add_input_listener(self, listener: Callable[[str], dict[str, Any] | None]) -> Callable[[], None]:
        """Add an input listener. Returns a function to remove the listener."""
        ...
    
    def request_render(self, force: bool = ..., *, reset_scrollback: bool = ...) -> None:
        """Request a render on next frame.

        Args:
            force: If True, force visible redraw (clears screen and
                resets differential cache)
            reset_scrollback: If True, reset scrollback tracking state.
                Use this when switching content entirely (e.g., after
                container.clear()) to ensure new content flows into
                terminal scrollback properly.
        """
        ...
    
    def handle_input(self, data: str) -> None:
        """Handle keyboard input - forwards to focused component.

        Call this from your main loop with data from terminal.read_sequence().
        """
        ...
    
    def reset_scrollback_state(self) -> None:
        """Reset scrollback tracking state.

        Call this when switching content entirely
        (e.g., after container.clear()) to ensure new content
        flows into terminal scrollback properly. This resets
        the internal counters that track which lines have been
        emitted to the terminal's native scrollback buffer.
        """
        ...
    
    def render_frame(self) -> None:
        """Render a single frame using absolute cursor positioning.

        Uses synchronized output (DEC 2026) to prevent flickering.
        """
        ...
    
    def run_frame(self) -> bool:
        """Run a single frame - process input and render.

        Returns:
            True if should continue, False if should stop.
        """
        ...
    
    def run(self) -> None:
        """Main run loop."""
        ...
    


