from _typeshed import Incomplete
from pypitui.component import Component as Component, Rect as Rect
from typing import Protocol

class TerminalProtocol(Protocol):
    def write(self, data: str | bytes) -> None: ...
    def move_cursor(self, col: int, row: int) -> None: ...
    def clear_line(self) -> None: ...
    def clear_screen(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...

class TUI:
    terminal: Incomplete
    def __init__(self, terminal: TerminalProtocol) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def invalidate_component(self, component: Component) -> None: ...
    def on_resize(self, _new_width: int, _new_height: int) -> None: ...
    def push_focus(self, component: Component | None) -> None: ...
    def pop_focus(self) -> Component | None: ...
    def set_focus(self, component: Component | None) -> None: ...
    def register_focusable(self, component: Component) -> None: ...
    def cycle_focus(self, direction: int = 1) -> None: ...

class LineOverflowError(Exception): ...
