"""Utility functions for terminal UI rendering."""

from collections.abc import Callable

def strip_ansi(text: str) -> str: ...
def visible_width(text: str) -> int: ...
def extract_ansi_code(text: str, pos: int) -> tuple[str, int] | None: ...
def wrap_text_with_ansi(text: str, width: int) -> list[str]: ...
def is_whitespace(char: str) -> bool: ...
def is_punctuation(char: str) -> bool: ...
def apply_background_to_line(
    line: str, width: int, bg_fn: Callable[[str], str]
) -> str: ...
def truncate_to_width(
    text: str, max_width: int, ellipsis: str = ..., pad: bool = ...
) -> str: ...
def slice_by_column(
    line: str, start_col: int, length: int, strict: bool = ...
) -> str: ...
def get_terminal_size() -> tuple[int, int]: ...
