"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable

"""
This type stub file was generated by pyright.
"""
CSI_PATTERN = ...
APC_PATTERN = ...
ANSI_PATTERN = ...
_segmenter: object | None = ...
def get_segmenter() -> object:
    """Get the shared grapheme segmenter instance."""
    ...

def strip_ansi(text: str) -> str:
    """Remove ANSI escape sequences from text."""
    ...

def visible_width(text: str) -> int:
    """Calculate the visible width of a string in terminal columns.

    Ignores ANSI escape codes and handles wide characters (emojis, CJK, etc.)
    using wcwidth for accurate terminal column counting.
    """
    ...

def extract_ansi_code(text: str, pos: int) -> tuple[str, int] | None:
    """Extract ANSI escape sequence from text at given position.

    Returns (code, length) or None if no code at position.
    """
    ...

def wrap_text_with_ansi(text: str, width: int) -> list[str]:
    """Wrap text preserving ANSI codes.

    Only does word wrapping - NO padding, NO background colors.
    Returns lines where each line is <= width visible chars.
    Active ANSI codes are preserved across line breaks.
    """
    ...

def is_whitespace(char: str) -> bool:
    """Check if a character is whitespace."""
    ...

def is_punctuation(char: str) -> bool:
    """Check if a character is punctuation."""
    ...

def apply_background_to_line(line: str, width: int, bg_fn: Callable[[str], str]) -> str:
    """Apply background color to a line, padding to full width.

    Args:
        line: Line of text (may contain ANSI codes)
        width: Total width to pad to
        bg_fn: Background color function

    Returns:
        Line with background applied and padded to width
    """
    ...

def truncate_to_width(text: str, max_width: int, ellipsis: str = ..., pad: bool = ...) -> str:
    """Truncate text to fit within a maximum visible width.

    Properly handles ANSI escape codes (they don't count toward width).

    Args:
        text: Text to truncate (may contain ANSI codes)
        max_width: Maximum visible width
        ellipsis: Ellipsis string when truncating (default: "...")
        pad: If True, pad result with spaces to exactly max_width

    Returns:
        Truncated text, optionally padded to exactly max_width
    """
    ...

def slice_by_column(line: str, start_col: int, length: int, strict: bool = ...) -> str:
    """Extract a range of visible columns from a line.

    Handles ANSI codes and wide characters properly.

    Args:
        line: Input line
        start_col: Starting column (0-indexed)
        length: Number of columns to extract
        strict: If True, exclude wide chars at boundary that would
            extend past range

    Returns:
        Extracted text with ANSI codes preserved
    """
    ...

def get_terminal_size() -> tuple[int, int]:
    """Get terminal size as (columns, rows)."""
    ...

