from pypitui.component import Component, RenderedLine, Size

class Container(Component):
    _children: list[Component]
    def __init__(self) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def clear_children(self) -> None: ...
    def measure(self, available_width: int, available_height: int) -> Size: ...
    def render(self, width: int) -> list[RenderedLine]: ...
