from ..component import Component as Component, RenderedLine as RenderedLine, Size as Size, StyleSpan as StyleSpan
from ..utils import truncate_to_width as truncate_to_width
from collections.abc import Callable as Callable
from dataclasses import dataclass
from typing import override

@dataclass
class Input(Component):
    placeholder: str = ...
    max_length: int = ...
    on_submit: Callable[[str], None] | None = ...
    @override
    def measure(self, available_width: int, available_height: int) -> Size: ...
    @override
    def render(self, width: int) -> list[RenderedLine]: ...
    def handle_input(self, data: bytes) -> bool: ...
    def get_cursor_position(self) -> tuple[int, int] | None: ...
