from pypitui.component import Component, RenderedLine, Size

class Text(Component):
    _text: str
    def __init__(self, text: str = ...) -> None: ...
    def get_text(self) -> str: ...
    def set_text(self, text: str) -> None: ...
    def measure(self, available_width: int, available_height: int) -> Size: ...
    def render(self, width: int) -> list[RenderedLine]: ...
