from .tui import Component as Component, Focusable as Focusable
from collections.abc import Callable as Callable
from dataclasses import dataclass

class Text(Component):
    def __init__(self, text: str = ..., padding_x: int = ..., padding_y: int = ..., custom_bg_fn: Callable[[str], str] | None = ...) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_custom_bg_fn(self, custom_bg_fn: Callable[[str], str] | None) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class Box(Component):
    children: list[Component]
    def __init__(self, padding_x: int = ..., padding_y: int = ..., bg_fn: Callable[[str], str] | None = ...) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def remove_child(self, component: Component) -> None: ...
    def clear(self) -> None: ...
    def set_bg_fn(self, bg_fn: Callable[[str], str] | None) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class BorderedBox(Component):
    children: list[Component]
    def __init__(self, padding_x: int = ..., padding_y: int = ..., min_width: int = ..., max_width: int | None = ..., title: str | None = ...) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_rich_title(self, markup: str) -> None: ...
    def add_child(self, component: Component) -> None: ...
    def remove_child(self, component: Component) -> None: ...
    def clear(self) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

class Spacer(Component):
    def __init__(self, height: int = ...) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...

@dataclass
class SelectItem:
    value: str
    label: str
    description: str | None = ...

@dataclass
class SelectListTheme:
    selected_prefix: Callable[[str], str] = ...
    selected_text: Callable[[str], str] = ...
    description: Callable[[str], str] = ...
    scroll_info: Callable[[str], str] = ...
    no_match: Callable[[str], str] = ...

class SelectList(Component):
    on_select: Callable[[SelectItem], None] | None
    on_cancel: Callable[[], None] | None
    on_selection_change: Callable[[SelectItem], None] | None
    def __init__(self, items: list[SelectItem], max_visible: int, theme: SelectListTheme) -> None: ...
    def set_filter(self, filter_text: str) -> None: ...
    def set_selected_index(self, index: int) -> None: ...
    def get_selected_item(self) -> SelectItem | None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...
    def handle_input(self, data: str) -> None: ...

class Input(Component, Focusable):
    on_submit: Callable[[str], None] | None
    on_cancel: Callable[[], None] | None
    def __init__(self, placeholder: str = ..., password: bool = ...) -> None: ...
    @property
    def focused(self) -> bool: ...
    @focused.setter
    def focused(self, value: bool) -> None: ...
    def get_value(self) -> str: ...
    def set_value(self, text: str) -> None: ...
    def invalidate(self) -> None: ...
    def render(self, width: int) -> list[str]: ...
    def handle_input(self, data: str) -> None: ...
